### ISSUE TITLE
crash au lancement, dépendance OpenSSL foireuse ?

### ISSUE THREAD

**Issue by darcosion** [darcosion/Echosounder#93]
Au lancement, aujourd'hui, j'ai découvert ceci : 
```bash
@:~$ sudo python3 webchosounder.py 
module 'lib' has no attribute 'OpenSSL_add_all_algorithms'
Traceback (most recent call last):
  File "~/Echosounder/dev/webchosounder.py", line 30, in <module>
    LOCAL_IP = get_if_addr(conf.iface)
  File "/usr/local/lib/python3.10/dist-packages/scapy/arch/__init__.py", line 73, in get_if_addr
    return inet_ntop(socket.AF_INET, get_if_raw_addr(iff))  # noqa: F405
  File "/usr/local/lib/python3.10/dist-packages/scapy/arch/linux.py", line 127, in get_if_raw_addr
    return get_if(iff, SIOCGIFADDR)[20:24]
  File "/usr/local/lib/python3.10/dist-packages/scapy/arch/unix.py", line 42, in get_if
    return ioctl(sck, cmd, struct.pack("16s16x", iff.encode("utf8")))
AttributeError: 'NoneType' object has no attribute 'encode'
```

**Comment by darcosion** [comment]
Apparemment, ça viens d'une incompatibilité entre le module `cryptography` et `pyopenssl`. Comme ce sont tout deux des dépendances de scapy, j'ai mis pyOpenSSL dans le requirements e2f02abf4076c192e6c692905671c1350629c240 de sorte à ce qu'il soit toujours le plus à jour. Pour cryptography, mieux vaut pas le mettre parce qu'il y a plusieurs versions de ce module qui se bataillent. ><
